// Generated by packages/physics/decomposers/build.sh: the C ABI of decomposers/results.h, as Emscripten exports it.
import type { DecomposerModule } from '../decompose.ts';
declare const loadVhacd: (options?: { print?: (text: string) => void; printErr?: (text: string) => void }) => Promise<DecomposerModule>;
export default loadVhacd;
