/**
 * Measures the advance width of every printable ASCII character in each bundled font (models/fonts) with OpenSCAD's own
 * `text()` and writes packages/contracts/src/textMetrics.ts. The contract uses it to reject text that would not fit the
 * underside of the cigarette case without needing a renderer. Regenerate after changing a font or the text size unit.
 *   npx tsx tools/generate-text-metrics.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createOpenSCAD } from 'openscad-wasm-prebuilt';
import { FONTS_DIR } from './stl-to-scad/openscad.ts';

const FONTS: Record<string, string> = {
  sans: 'Liberation Sans:style=Bold', serif: 'Liberation Serif:style=Bold', mono: 'Liberation Mono:style=Bold', wide: 'DejaVu Sans:style=Bold',
};
const UNIT = 10; // measured at text size 10, stored per 1 mm of size

async function instance() {
  const lines: string[] = [];
  const openscad = (await createOpenSCAD({ print: line => lines.push(line), printErr: line => lines.push(line) })).getInstance();
  for (const dir of ['/fonts', '/etc', '/etc/fonts']) openscad.FS.mkdir(dir);
  for (const font of readdirSync(FONTS_DIR).filter(name => name.endsWith('.ttf'))) openscad.FS.writeFile(`/fonts/${font}`, readFileSync(join(FONTS_DIR, font)));
  openscad.FS.writeFile('/etc/fonts/fonts.conf', '<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><dir>/fonts</dir></fontconfig>');
  return { openscad, lines };
}

async function bounds(font: string, text: string): Promise<{ width: number; minY: number; maxY: number }> {
  const { openscad, lines } = await instance();
  openscad.FS.writeFile('/m.scad', `linear_extrude(1) text(${JSON.stringify(text)}, size = ${UNIT}, font = ${JSON.stringify(font)});`);
  openscad.callMain(['/m.scad', '--backend=Manifold', '--export-format', 'binstl', '-o', '/o.stl']);
  const stl = Buffer.from(openscad.FS.readFile('/o.stl'));
  const count = stl.readUInt32LE(80);
  if (count === 0) throw new Error(`No geometry for ${JSON.stringify(text)} in ${font}: ${lines.slice(-3).join(' | ')}`);
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (let i = 0; i < count; i++) for (let v = 0; v < 3; v++) {
    const offset = 84 + i * 50 + 12 + v * 12;
    const x = stl.readFloatLE(offset), y = stl.readFloatLE(offset + 4);
    minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y);
  }
  return { width: maxX - minX, minY, maxY };
}

const round = (value: number) => Math.round(value * 1000) / 1000;
const advances: Record<string, Record<string, number>> = {};
const extents: Record<string, { below: number; above: number }> = {};
for (const [key, font] of Object.entries(FONTS)) {
  const base = (await bounds(font, '||')).width;
  const table: Record<string, number> = {};
  advances[key] = table;
  let below = 0, above = 0;
  for (let code = 32; code <= 126; code++) {
    const char = String.fromCharCode(code);
    const measured = await bounds(font, `|${char}|`);
    table[char] = round((measured.width - base) / UNIT);
    if (char !== ' ') { below = Math.min(below, measured.minY); above = Math.max(above, measured.maxY); }
  }
  extents[key] = { below: round(below / UNIT), above: round(above / UNIT) };
  console.log(key, 'space', table['M'], 'height per mm of size:', extents[key]);
}
const body = `// Generated by tools/generate-text-metrics.ts from the fonts in models/fonts. Do not edit by hand.
/** Advance width of each printable ASCII character, per millimetre of OpenSCAD text size, for each bundled font. */
export const TEXT_ADVANCES: Record<string, Record<string, number>> = ${JSON.stringify(advances)};
/** The lowest and highest point of any printable ASCII glyph above the baseline, per millimetre of text size (below is negative). */
export const TEXT_EXTENTS: Record<string, { below: number; above: number }> = ${JSON.stringify(extents)};
`;
writeFileSync(new URL('../packages/contracts/src/textMetrics.ts', import.meta.url), body);
